categorias_seed = [
  {
    "categoria": "ALIMENTACAO",
    "descricoes": [
      "Supermercado", "supermerc", "iFood", "Restaurante", "Padaria",
      "Lanche na padaria", "Feira livre", "Marmita", "Almoço no self-service",
      "Hortifruti", "Açougue", "Pizza delivery 🍕", "Mercadinho da esquina",
      "Café da manhã", "Rappi comida", "Sacolão", "Restaurante japonês",
      "Boteco", "Padoca", "Doceria", "Hamburgueria", "Sushi", "Lanchonete",
      "Quentinha", "Churrascaria", "Cantina", "Confeitaria", "Mercado Extra",
      "Pão de Açúcar", "Carrefour compras", "Assaí atacadista", "Big compras mês",
      "Sorveteria", "Cafeteria", "Starbucks", "Delivery japonês",
      "Rodízio de pizza", "Comida japonesa", "Empório", "Casa de sucos",
      "Tapiocaria", "Food truck", "Feira do produtor", "Mercearia",
      "Compra do mês", "Almoço executivo", "Ceia de natal", "Café da tarde",
      "Kg de carne açougue", "Padaria pão quentinho", "Sorvete no shopping",
      "iFood lanche da noite", "Marmita fit", "Empada de padaria", "Coxinha na padaria",
      "Pastelaria", "Feira de orgânicos", "Mercado Dia", "Mercado São Luiz",
      "Compra de carne para o mês", "Peixaria", "Rotisserie", "Buffet a quilo",
      "Restaurante árabe", "Comida mexicana", "Comida italiana", "Massas artesanais",
      "Padaria integral", "Loja de conveniência", "Posto - loja de conveniência",
      "Café expresso", "Chá da tarde", "Chocolateria", "Brigaderia",
      "Casaca de vinho e queijo", "Empório de frios", "Quitanda", "Frutaria",
      "Rappi mercado", "iFood mercado", "Compra de bebidas para festa",
      "Salgados para festa", "Encomenda de bolo", "Bolo de aniversário",
      "Doces personalizados", "Marmitex semanal", "Almoço em viagem a trabalho",
      "Jantar delivery", "Vinho para o jantar", "Cerveja no mercado",
      "Água e refrigerante mercado", "Padaria café da manhã reunião",
      "Buffet de casamento", "Compra de tempero e especiarias",
      "Loja de produtos naturais", "Suplemento alimentar mercado",
      "Ovos e laticínios", "Compra de pão integral", "Marmita congelada",
      "Restaurante vegano", "Comida saudável fit"
    ],
    "faixa_valor": {"min": 400, "max": 2_000},
    "armadilhas": [
      {"descricao": "Farmácia e Mercado", "pode_confundir_com": "Saúde", "motivo": "compra combinada em supermercados com farmácia interna"},
      {"descricao": "Padaria - pão e remédio", "pode_confundir_com": "Saúde", "motivo": "padarias vendem itens de conveniência incluindo medicamentos simples"},
      {"descricao": "Jantar de aniversário", "pode_confundir_com": "Lazer", "motivo": "refeição associada a comemoração/evento social"}
    ]
  },
  {
    "categoria": "TRANSPORTE",
    "descricoes": [
      "Uber", "99 ida trab", "Gasolina", "Posto Ipiranga", "Ônibus",
      "Estacionamento shopping", "Pedágio", "Metrô", "Bilhete único",
      "Revisão do carro", "Táxi", "Uber moto", "Seguro do carro",
      "Troca de óleo", "Multa de trânsito", "IPVA", "Combustível",
      "Recarga bilhete", "InDriver", "Patinete elétrico", "Uber volta casa",
      "Posto Shell", "Estacionamento rotativo", "Zona azul", "Alinhamento e balanceamento",
      "Troca de pneu", "Bicicleta compartilhada", "Van escolar", "Fretado empresa",
      "Aplicativo de transporte", "Motoboy próprio", "Aluguel de carro",
      "Locadora de veículo", "Guincho", "Seguro de moto", "Combustível moto",
      "Estacionamento aeroporto", "Passagem de ônibus intermunicipal",
      "Bilhete metrô recarga", "Uber pra faculdade", "Corrida de app",
      "Vistoria veicular", "Lavagem do carro", "Carro por assinatura",
      "Multa de estacionamento", "Seguro DPVAT", "Documentação do carro",
      "Transporte escolar", "Carona paga", "Corrida 99",
      "Uber para o trabalho", "99 pop", "Combustível etanol", "Posto BR", "Posto Ale",
      "Recarga do carro elétrico", "Estação de recarga elétrica", "Seguro de bicicleta",
      "Manutenção de moto", "Troca de correia dentada", "Revisão programada concessionária",
      "Multa por excesso de velocidade", "Licenciamento anual", "Emplacamento",
      "Transferência de veículo", "Seguro de carro terceiro", "Estacionamento de shopping mensal",
      "Vale transporte", "Cartão de transporte recarga", "Passagem de trem",
      "Passagem de barca", "Travessia balsa", "Aluguel de patinete", "Uber Black",
      "Uber Comfort", "99 taxi", "InDriver corrida", "Cabify", "Frete de mudança",
      "Motorista de aplicativo gorjeta", "Corrida de van compartilhada", "Aluguel de moto",
      "Aluguel de bike elétrica", "Pedágio viagem", "Estacionamento rodoviária",
      "Estacionamento hospital", "Combustível viagem de férias", "Troca de bateria do carro",
      "Troca de amortecedor", "Alinhamento de direção", "Seguro de carro anual",
      "Multa de rodízio", "IPVA parcelado", "Licenciamento moto",
      "Seguro de vida do motorista de app", "Documentação de transferência",
      "Vistoria detran", "Estacionamento aeroporto internacional",
      "Corrida de app para aeroporto", "Passagem de ônibus interestadual"
    ],
    "faixa_valor": {"min": 4, "max": 500},
    "armadilhas": [
      {"descricao": "IPVA", "pode_confundir_com": "Dívidas", "motivo": "é um imposto obrigatório, pode parecer taxa/dívida em vez de custo de transporte"},
      {"descricao": "Seguro do carro", "pode_confundir_com": "Serviços", "motivo": "seguro é uma prestação de serviço recorrente, não desgaste direto do veículo"},
      {"descricao": "Uber para o hospital", "pode_confundir_com": "Saúde", "motivo": "o motivo da viagem é de saúde, mas o gasto em si é de transporte"}
    ]
  },
  {
    "categoria": "SAUDE",
    "descricoes": [
      "Farmácia", "Droga Raia", "Consulta médica", "Plano de saúde",
      "Academia", "acad", "Exame de sangue", "Fisioterapia",
      "Consulta psicólogo", "Dentista", "Óculos de grau", "Remédio",
      "Vacina", "Nutricionista", "Suplemento", "Whey protein 💪",
      "Consulta oftalmo", "Personal trainer", "Exame de imagem", "Vitaminas",
      "Droga Raia farmácia", "Drogasil", "Pague Menos", "Consulta dermato",
      "Exame de rotina", "Check-up anual", "Terapia semanal", "Ortopedista",
      "Cirurgia eletiva", "Aparelho ortodôntico", "Clareamento dental",
      "Aplicação de botox", "Sessão de acupuntura", "Pilates", "Yoga aula",
      "Massoterapia", "Consulta ginecologista", "Consulta pediatra filho",
      "Homeopatia", "Consulta nutricional", "Aparelho auditivo",
      "Lente de contato", "Protetor solar farmácia", "Teste covid",
      "Vacina gripe", "Plano odontológico", "Fralda geriátrica",
      "Cadeira de rodas aluguel", "Fonoaudiólogo", "Consulta psiquiátrica",
      "Consulta cardiologista", "Consulta neurologista", "Consulta urologista",
      "Consulta otorrino", "Exame de urina", "Exame de fezes", "Ultrassom",
      "Raio-x", "Tomografia", "Ressonância magnética", "Mamografia",
      "Densitometria óssea", "Vacina febre amarela", "Vacina HPV",
      "Suplemento vitamina D", "Suplemento ômega 3", "Colágeno em pó",
      "Consulta endocrinologista", "Consulta reumatologista", "Sessão de RPG",
      "Sessão de quiropraxia", "Aparelho de surdez manutenção",
      "Óculos de sol com grau", "Cirurgia de catarata", "Consulta oncologista",
      "Sessão de radioterapia", "Sessão de quimioterapia", "Plano de saúde dependente",
      "Coparticipação plano de saúde", "Farmácia popular", "Extrafarma",
      "Farmácia São João", "Compra de máscara e álcool gel", "Termômetro digital",
      "Aparelho de pressão", "Glicosímetro", "Tiras de glicemia", "Fralda infantil",
      "Leite especial bebê", "Consulta veterinária", "Vacina do pet",
      "Ração medicamentosa pet", "Sessão de terapia de casal",
      "Sessão de terapia ocupacional", "Consulta com nutrólogo", "Bota ortopédica",
      "Muleta aluguel", "Andador aluguel", "Consulta de retorno",
      "Encaixe de emergência médica"
    ],
    "faixa_valor": {"min": 15, "max": 1_000},
    "armadilhas": [
      {"descricao": "Whey protein", "pode_confundir_com": "Alimentação", "motivo": "é um suplemento alimentar, pode ser confundido com compra de mercado"},
      {"descricao": "Personal trainer", "pode_confundir_com": "Lazer", "motivo": "atividade física pode ser vista como hobby em vez de cuidado com saúde"},
      {"descricao": "Plano de saúde", "pode_confundir_com": "Assinaturas", "motivo": "é uma mensalidade recorrente, parecido com estrutura de assinatura"}
    ]
  },
  {
    "categoria": "MORADIA",
    "descricoes": [
      "Aluguel", "Condomínio", "Conta de luz", "Conta de água", "Conta de gás",
      "Internet residencial", "Mobília", "Reforma", "Material de construção",
      "IPTU", "Taxa de condomínio", "Móveis planejados", "Pintura da casa",
      "Encanamento", "Seguro residencial", "Portão eletrônico", "Cortina",
      "Ar-condicionado", "Chaveiro emergencial", "Dedetização",
      "Botijão de gás", "Conta de luz Enel", "Conta Sabesp", "Faxina pesada",
      "Colchão novo", "Sofá novo", "Eletrodoméstico", "Geladeira nova",
      "Fogão novo", "Máquina de lavar", "Persiana", "Tapete", "Armário embutido",
      "Instalação elétrica", "Troca de fechadura", "Vaso sanitário",
      "Torneira nova", "Piso novo", "Telhado conserto", "Jardinagem",
      "Manutenção do portão", "Câmera de segurança", "Alarme residencial",
      "Interfone", "Aluguel de imóvel comercial", "Taxa de água condomínio",
      "Rateio extra condomínio", "Síndico profissional", "Seguro incêndio",
      "Reforma do banheiro",
      "Conta de internet fibra", "Conta de telefone fixo", "Assinatura de TV a cabo",
      "Reforma da cozinha", "Reforma da varanda", "Impermeabilização de laje",
      "Troca de telha", "Pintura externa", "Revestimento de parede",
      "Instalação de piso laminado", "Instalação de porcelanato", "Móveis de jardim",
      "Churrasqueira nova", "Instalação de churrasqueira", "Reparo de portão automático",
      "Manutenção de ar-condicionado", "Recarga de gás do ar-condicionado",
      "Filtro de água troca", "Purificador de água", "Bomba d'água conserto",
      "Caixa d'água limpeza", "Poço artesiano manutenção", "Aluguel de temporada",
      "Depósito de aluguel (caução)", "Taxa de mudança", "Frete de móveis",
      "Seguro fiança", "Corretora de imóveis comissão", "Escritura do imóvel",
      "Registro de imóvel cartório", "Laudo de vistoria imóvel", "Reparo de vazamento",
      "Desentupimento de esgoto", "Conserto de telhado após chuva",
      "Instalação de painel solar", "Manutenção de painel solar", "Conta de gás encanado",
      "Taxa de lixo municipal", "Taxa extra de reforma condominial",
      "Fundo de reserva condominial", "Multa condominial", "Assembleia condominial taxa",
      "Portaria 24h taxa", "Zelador gorjeta", "Reforma elétrica completa",
      "Troca de disjuntor", "Instalação de tomadas", "Cortina blackout",
      "Persiana motorizada", "Redecoração da sala"
    ],
    "faixa_valor": {"min": 40, "max": 2_800},
    "armadilhas": [
      {"descricao": "Encanamento", "pode_confundir_com": "Serviços", "motivo": "conserto de encanamento é mão de obra, pode parecer serviço avulso"},
      {"descricao": "Chaveiro emergencial", "pode_confundir_com": "Serviços", "motivo": "é prestação pontual de serviço, não custo fixo de moradia"},
      {"descricao": "Seguro residencial", "pode_confundir_com": "Assinaturas", "motivo": "cobrança mensal recorrente parecida com assinatura"}
    ]
  },
  {
    "categoria": "EDUCACAO",
    "descricoes": [
      "Mensalidade faculdade", "Curso online", "Escola dos filhos",
      "Material didático", "Curso de inglês", "Livro técnico",
      "Mensalidade escolar", "Certificação profissional", "Udemy",
      "Curso técnico", "Apostila", "Aula particular", "Curso de programação",
      "Pós-graduação", "MBA", "Papelaria escolar", "Uniforme escolar",
      "Kumon", "Curso preparatório", "Inscrição em concurso",
      "Mensalidade cursinho", "Curso de espanhol", "Aula de reforço",
      "Faculdade EAD", "Mensalidade pós", "Curso de excel", "Curso de design",
      "Livro de faculdade", "Xerox apostila", "Inscrição vestibular",
      "Taxa de matrícula", "Curso de culinária", "Curso de música",
      "Aula de violão", "Aula de canto", "Curso de fotografia",
      "Workshop profissional", "Congresso acadêmico", "Palestra paga",
      "Curso de libras", "Mensalidade intercâmbio", "Aula de reforço matemática",
      "Kit escolar", "Mochila escolar", "Livro paradidático",
      "Assinatura biblioteca digital", "Curso de marketing digital",
      "Certificação AWS", "Curso de dados", "Mensalidade curso técnico",
      "Curso de inglês online", "Curso de alemão", "Curso de francês",
      "Curso de mandarim", "Aula de reforço português", "Aula de reforço redação",
      "Curso de robótica infantil", "Curso de lógica de programação",
      "Bootcamp de tecnologia", "Curso de UX design", "Curso de gestão de projetos",
      "Certificação PMP", "Certificação Scrum Master", "Curso de Google Ads",
      "Curso de SEO", "Curso de edição de vídeo", "Curso de ilustração digital",
      "Material de desenho", "Compasso e material geométrico",
      "Calculadora científica", "Notebook para faculdade", "Tablet para estudos",
      "Impressão de TCC", "Encadernação de trabalho", "Taxa de emissão de diploma",
      "Colação de grau taxa", "Taxa de segunda chamada de prova",
      "Curso preparatório ENEM", "Curso de redação ENEM", "Simulado pago",
      "Aula de reforço química", "Aula de reforço física", "Aula de reforço biologia",
      "Curso técnico em enfermagem", "Curso técnico em administração",
      "Pós-graduação EAD", "Mestrado profissional mensalidade",
      "Curso de idiomas intercâmbio", "Material de artes",
      "Uniforme de educação física", "Livro de literatura obrigatório",
      "Assinatura de plataforma de estudos", "Aplicativo de aprendizado pago",
      "Curso de direito trabalhista", "Curso de finanças pessoais",
      "Curso de oratória", "Curso de liderança", "Curso de excel avançado",
      "Curso de power bi", "Certificação Scrum"
    ],
    "faixa_valor": {"min": 20, "max": 2_000},
    "armadilhas": [
      {"descricao": "Papelaria escolar", "pode_confundir_com": "Outras", "motivo": "compra pontual de material pode parecer gasto avulso genérico"},
      {"descricao": "Curso de inglês", "pode_confundir_com": "Assinaturas", "motivo": "cursos online por assinatura mensal (ex: apps de idiomas) se confundem com assinatura pura"},
      {"descricao": "Uniforme escolar", "pode_confundir_com": "Outras", "motivo": "compra de vestuário específico pode ser categorizada como item avulso"}
    ]
  },
  {
    "categoria": "LAZER",
    "descricoes": [
      "Cinema", "Jogo digital", "Livro", "Show", "Viagem", "Passeio no parque",
      "Bar com amigos", "Parque de diversões", "Ingresso de evento",
      "Balada", "Steam sale 🎮", "Aluguel de filme", "Boliche",
      "Karaokê", "Passeio de barco", "Zoológico", "Museu",
      "Festival de música", "Escape room", "Compra de skin de jogo",
      "Playstation Store", "Xbox loja", "Ingresso teatro", "Parque aquático",
      "Passeio de trilha", "Acampamento", "Praia final de semana",
      "Hospedagem Airbnb", "Passagem aérea viagem", "Aluguel de bike",
      "Pescaria", "Barzinho", "Happy hour", "Festa junina",
      "Ingresso de circo", "Kart", "Sinuca", "Jogo de tabuleiro",
      "Cervejaria artesanal", "Vinho especial", "Compra de vinil",
      "Convenção de games", "Comic con ingresso", "Passeio ciclístico",
      "Aluguel de casa de praia", "Passeio de lancha", "Aquário municipal",
      "Show de stand-up", "Ingresso de festival", "Camping",
      "Cinema com pipoca", "Sessão IMAX", "Ingresso de parque temático",
      "Viagem de fim de semana", "Passeio de teleférico", "Passeio de helicóptero",
      "Mergulho recreativo", "Aula de surf", "Aluguel de prancha",
      "Aluguel de caiaque", "Rafting", "Tirolesa", "Passeio de quadriciclo",
      "Show de rock", "Show de sertanejo", "Festival de cerveja",
      "Feira de food trucks", "Parque de trampolim", "Sala de fuga",
      "Jogo de realidade virtual", "Fliperama", "Cinema drive-in",
      "Peça de teatro infantil", "Espetáculo de dança", "Balé ingresso",
      "Ópera ingresso", "Exposição de arte", "Feira de artesanato",
      "Parque nacional entrada", "Trilha guiada", "Passeio de bicicleta em grupo",
      "Torneio de videogame", "Aluguel de jogo de tabuleiro",
      "Clube de xadrez mensalidade", "Sinuca e bilhar", "Fliperama de bar",
      "Compra de jogo Nintendo Switch", "Compra de jogo PS5", "DLC de jogo",
      "Assinatura de jogo mobile", "Rolê de fim de semana", "Show em casa de shows",
      "Ingresso de festa eletrônica", "Réveillon em pousada",
      "Carnaval fora de época viagem", "Passeio a cavalo", "Passeio de balão",
      "Aluguel de casa em condomínio de praia", "Cruzeiro marítimo",
      "Passeio turístico guiado"
    ],
    "faixa_valor": {"min": 10, "max": 1_500},
    "armadilhas": [
      {"descricao": "Bar com amigos", "pode_confundir_com": "Alimentação", "motivo": "envolve consumo de comida e bebida, pode parecer gasto alimentar"},
      {"descricao": "Viagem", "pode_confundir_com": "Transporte", "motivo": "inclui passagens e deslocamento, sobreposição com custos de transporte"},
      {"descricao": "Museu", "pode_confundir_com": "Educação", "motivo": "cunho cultural/educativo pode ser interpretado como despesa educacional"}
    ]
  },
  {
    "categoria": "SERVICOS",
    "descricoes": [
      "Diarista", "Encanador", "Cabeleireiro", "Manicure", "Eletricista",
      "Lavanderia", "Costureira", "Chaveiro", "Pedreiro", "Jardineiro",
      "Pet shop banho e tosa", "Passadeira", "Marido de aluguel",
      "Técnico de informática", "Motoboy entrega", "Fotógrafo",
      "Serviço de mudança", "Dedetizador", "Reparo de celular", "Assistência técnica",
      "Barbeiro", "Depilação", "Design de sobrancelha", "Maquiadora",
      "Personal organizer", "Faxina semanal", "Piscineiro", "Marceneiro",
      "Vidraceiro", "Gesseiro", "Pintor de parede", "Instalador de ar-condicionado",
      "Técnico de TV", "Conserto de máquina de lavar", "Costura de roupa",
      "Ajuste de calça", "Revisão de sapato sapataria", "Gravação de evento",
      "Cerimonialista", "DJ para festa", "Buffet contratado",
      "Segurança de evento", "Motorista particular", "Tradutor freelancer",
      "Contador autônomo", "Advogado consulta", "Consultoria financeira",
      "Serviço de streaming de conteúdo próprio", "Manutenção de piscina",
      "Instalação de câmeras", "Aula de reforço doméstica",
      "Passadeira semanal", "Jardinagem mensal", "Poda de árvores",
      "Limpeza de caixa d'água", "Dedetização de pragas", "Higienização de estofado",
      "Higienização de colchão", "Lavagem de tapete", "Conserto de guarda-chuva",
      "Conserto de mala de viagem", "Serviço de costura sob medida",
      "Ajuste de vestido de festa", "Bordado personalizado", "Fotografia de evento",
      "Filmagem de casamento", "Edição de vídeo freelancer",
      "Design gráfico freelancer", "Social media freelancer",
      "Consultoria de marketing", "Consultoria jurídica", "Serviço de despachante",
      "Serviço de tradução juramentada", "Notário reconhecimento de firma",
      "Serviço de motoboy documentos", "Conserto de bicicleta",
      "Manutenção de patinete elétrico", "Serviço de manicure a domicílio",
      "Serviço de cabeleireiro a domicílio", "Massagem relaxante a domicílio",
      "Personal stylist", "Consultoria de imagem", "Serviço de organização de casamento",
      "Buffet infantil", "Decoração de festa", "Aluguel de som para evento",
      "Aluguel de mesa e cadeira para evento", "Garçom para evento",
      "Segurança particular", "Diarista quinzenal", "Passadeira de roupa de cama",
      "Conserto de eletrodoméstico", "Instalação de TV na parede",
      "Configuração de home theater", "Suporte técnico remoto",
      "Formatação de computador", "Instalação de software", "Serviço de pet sitter",
      "Passeio com cachorro", "Hospedagem de pet", "Adestrador de cães"
    ],
    "faixa_valor": {"min": 15, "max": 500},
    "armadilhas": [
      {"descricao": "Pet shop banho e tosa", "pode_confundir_com": "Outras", "motivo": "sem categoria de 'pets' dedicada, pode ser mal classificado como item genérico"},
      {"descricao": "Reparo de celular", "pode_confundir_com": "Outras", "motivo": "conserto de eletrônico pode parecer compra avulsa não recorrente"},
      {"descricao": "Dedetizador", "pode_confundir_com": "Moradia", "motivo": "está ligado à manutenção da casa, podendo ser visto como custo de moradia"}
    ]
  },
  {
    "categoria": "ASSINATURAS",
    "descricoes": [
      "Netflix", "Spotify", "iCloud", "Amazon Prime", "Disney+",
      "YouTube Premium", "HBO Max", "Software de edição", "Adobe Creative Cloud",
      "Xbox Game Pass", "PlayStation Plus", "Globoplay", "Deezer",
      "Apple Music", "Dropbox", "Canva Pro", "ChatGPT Plus", "Duolingo Plus",
      "Kindle Unlimited", "Paramount+", "Crunchyroll", "Star+",
      "Google One", "Microsoft 365", "Notion Pro", "Spotify Family",
      "Apple TV+", "Twitch subscription", "Discord Nitro", "iFood clube",
      "Amazon Music", "Audible", "Assinatura de revista digital",
      "VPN premium", "Antivírus anual", "Assinatura de app de treino",
      "Assinatura clube de vinhos", "Clube de assinatura de livros",
      "Assinatura barbearia mensal", "Peloton app", "Headspace premium",
      "Calm app assinatura", "Tinder Gold", "LinkedIn Premium",
      "Assinatura de jornal online", "Globo News assinatura",
      "Steam Deck plano", "Nuuvem clube", "Xbox Live Gold",
      "Assinatura de café mensal", "Clube de assinatura de queijos",
      "Max streaming", "Prime Video", "Looke streaming", "Mubi", "Telecine",
      "Now streaming", "Claro Video", "Globoplay com canais", "Spotify individual",
      "YouTube Music", "Tidal", "SoundCloud Go", "iFood plus", "Rappi Prime",
      "Uber One", "Amazon Prime anual", "iCloud+ armazenamento",
      "Google Drive plano pago", "Notion times", "Trello premium",
      "Slack premium", "Zoom premium", "Grammarly premium", "Perplexity Pro",
      "Claude Pro", "Gemini Advanced", "Microsoft 365 família", "Norton 360",
      "Kaspersky antivírus", "NordVPN", "ExpressVPN", "Aplicativo de meditação",
      "Strava premium", "Aplicativo de dieta premium", "MyFitnessPal premium",
      "Clube de assinatura de café especial", "Clube de assinatura de chocolates",
      "Clube de assinatura de cerveja artesanal", "Glambox assinatura",
      "Wine.com.br clube", "Revista Veja digital", "Revista Exame digital",
      "The New York Times digital", "Financial Times digital",
      "Canal de TV por assinatura extra", "Pacote de canais esportivos",
      "DAZN assinatura", "ESPN app assinatura", "Xbox Game Pass Ultimate",
      "Caixa de assinatura de beleza mensal"
    ],
    "faixa_valor": {"min": 9, "max": 150},
    "armadilhas": [
      {"descricao": "Xbox Game Pass", "pode_confundir_com": "Lazer", "motivo": "é uma assinatura, mas o conteúdo consumido (jogos) remete a lazer"},
      {"descricao": "Adobe Creative Cloud", "pode_confundir_com": "Educação", "motivo": "pode ser usado para fins de estudo/profissionalização, gerando ambiguidade de propósito"},
      {"descricao": "ChatGPT Plus", "pode_confundir_com": "Serviços", "motivo": "ferramenta de produtividade paga pode parecer prestação de serviço"}
    ]
  },
  {
    "categoria": "DIVIDAS",
    "descricoes": [
      "Financiamento do carro", "Financiamento da casa", "Fatura antiga do cartão",
      "Juros de empréstimo", "Taxa de cancelamento", "Parcela de empréstimo pessoal",
      "Renegociação de dívida", "Empréstimo consignado", "Cheque especial",
      "Juros rotativo cartão", "Acordo com credor", "Parcelamento de dívida",
      "Empréstimo com amigo", "Dívida em atraso", "Multa contratual",
      "Empréstimo estudantil", "Financiamento de móveis", "Consórcio",
      "Empréstimo no banco", "Refinanciamento", "Parcela do celular financiado",
      "Cartão de loja parcelado", "Empréstimo via app", "Dívida com fornecedor",
      "Acordo trabalhista pagamento", "Parcela do computador financiado",
      "Empréstimo para reforma", "Juros de atraso boleto", "Negativação renegociada",
      "Empréstimo consignado INSS", "Financiamento estudantil FIES",
      "Parcelamento de dívida fiscal", "Dívida antiga de faculdade",
      "Empréstimo pessoal banco digital", "Juros de cartão internacional",
      "Parcela do celular", "Dívida de cartão em atraso", "Empréstimo emergencial",
      "Empréstimo para capital de giro", "Cobrança judicial parcela",
      "Acordo extrajudicial", "Empréstimo peer-to-peer", "Dívida de faculdade particular",
      "Parcelamento de multa de trânsito", "Empréstimo garantido por imóvel",
      "Dívida antiga renegociada banco", "Empréstimo para viagem parcelado",
      "Financiamento de equipamento", "Parcela atrasada loja", "Empréstimo familiar",
      "Financiamento de moto", "Financiamento estudantil privado",
      "Parcela do curso técnico", "Dívida de cartão de crédito internacional",
      "Anuidade de cartão parcelada", "Empréstimo entre familiares",
      "Empréstimo consignado privado", "Empréstimo hipotecário",
      "Refinanciamento imobiliário", "Parcela de empréstimo veicular",
      "Multa de contrato rescindido", "Dívida de aluguel atrasado",
      "Dívida de condomínio atrasada", "Acordo de pagamento de dívida antiga",
      "Empréstimo para quitar outra dívida", "Empréstimo consignado servidor público",
      "Cartão consignado", "Rotativo do cartão", "Parcelamento de compra em atraso",
      "Dívida de cheque devolvido", "Taxa de juros de atraso IPTU",
      "Dívida de IPVA atrasado", "Multa e juros de imposto de renda",
      "Parcelamento de imposto atrasado", "Empréstimo para pagar dívida de cartão",
      "Negociação Serasa", "Negociação SPC", "Dívida judicial trabalhista",
      "Pensão alimentícia em atraso", "Empréstimo consignado aposentado",
      "Dívida com loja de departamento", "Crediário parcelado",
      "Dívida com clínica odontológica", "Financiamento de tratamento dentário",
      "Empréstimo para cirurgia", "Dívida com escola particular",
      "Parcelamento de material escolar", "Empréstimo para casamento",
      "Financiamento de festa de casamento", "Dívida com fornecedor de obra",
      "Empréstimo para pequena empresa", "Antecipação de recebíveis",
      "Empréstimo com garantia de veículo", "Empréstimo online rápido",
      "Empréstimo de fintech", "Parcela de consórcio atrasada",
      "Multa de cancelamento de consórcio", "Dívida com cartão de loja atrasado",
      "Empréstimo para viagem de formatura", "Renegociação de dívida bancária antiga"
    ],
    "faixa_valor": {"min": 40, "max": 4_000},
    "armadilhas": [
      {"descricao": "Financiamento de móveis", "pode_confundir_com": "Moradia", "motivo": "compra relacionada à casa, mas o gasto em si é a parcela de uma dívida"},
      {"descricao": "Consórcio", "pode_confundir_com": "Outras", "motivo": "consórcio tem características de poupança programada, ambíguo entre dívida e investimento"},
      {"descricao": "Empréstimo estudantil", "pode_confundir_com": "Educação", "motivo": "está ligado a estudos, mas o gasto é o pagamento da dívida, não a mensalidade em si"}
    ]
  },
  {
    "categoria": "POUPANCA",
    "descricoes": [
      "Aporte Tesouro Direto", "Compra de ações", "Aplicação CDB", "Aporte fundo imobiliário",
      "Compra de criptomoeda", "Aporte previdência privada", "Aplicação poupança",
      "Compra de ETF", "Aporte fundo multimercado", "Compra de dólar investimento",
      "Aporte mensal carteira", "Aplicação LCI", "Aplicação LCA", "Compra de Bitcoin",
      "Compra de Ethereum", "Aporte renda fixa", "Aporte ações internacionais",
      "Compra de FIIs", "Aplicação em COE", "Aporte clube de investimento",
      "aporte mensal", "compra acoes", "tesouro direto", "invest mensal",
      "Aplicação CDB banco digital", "Compra de fundo de índice", "Aporte previdência PGBL",
      "Aporte previdência VGBL", "Compra de ações XP", "Compra de ações Nubank",
      "Aplicação em debêntures", "Aporte fundo de ações", "Compra de ouro investimento",
      "Aporte carteira internacional", "Transferência para corretora", "Aplicação CDI",
      "Compra de ações Vale", "Compra de ações Petrobras", "Aporte fundo cambial",
      "Investimento em startups", "Aplicação em fundo de previdência",
      "Compra de moedas estrangeiras investimento", "Aporte reserva de emergência",
      "Compra de NFT investimento", "Aporte plano de aposentadoria",
      "Aplicação renda fixa prefixada", "Aporte fundo de crédito privado",
      "Compra de títulos públicos", "Investimento em consórcio de imóvel",
      "Transferência para conta investimento",
      "Depósito na poupança", "Aporte em CDB de banco digital", "Compra de Tesouro Selic",
      "Compra de Tesouro IPCA+", "Compra de Tesouro Prefixado", "Aporte em fundo DI",
      "Aporte em fundo de renda fixa", "Reserva de emergência mensal",
      "Aporte em poupança programada", "Aporte em previdência privada PGBL",
      "Compra de ações da bolsa americana", "Compra de ETF internacional (BDR)",
      "Aporte em fundo cambial dólar", "Compra de Solana", "Compra de outras criptomoedas",
      "Staking de criptomoeda", "Aporte em fundo imobiliário de tijolo",
      "Aporte em fundo imobiliário de papel", "Compra de LCI banco digital",
      "Compra de LCA cooperativa", "Aporte em CDB com liquidez diária",
      "Aporte em CDB de 2 anos", "Compra de debênture incentivada",
      "Aporte em previdência VGBL", "Investimento em fundo de crédito",
      "Compra de ações de dividendos", "Reinvestimento de dividendos",
      "Compra de ouro digital", "Aporte em fundo internacional",
      "Transferência para conta em corretora internacional",
      "Aporte em fundo de ações small caps", "Investimento em consórcio de veículo",
      "Aporte para meta de viagem", "Aporte para reserva de aposentadoria",
      "Compra de título prefixado longo prazo", "Compra de título pós-fixado",
      "Aporte em carteira recomendada", "Investimento em fundo ESG",
      "Aporte para independência financeira", "Compra de ações fracionárias",
      "Aporte em fundo multimercado macro", "Investimento em previdência aberta",
      "Compra de cotas de fundo de investimento", "Aporte automático mensal investimento",
      "Transferência para corretora XP", "Transferência para corretora Rico",
      "Transferência para corretora Clear", "Aporte em fundo cambial euro",
      "Compra de NFT como colecionável investimento", "Reserva programada para objetivo financeiro"
    ],
    "faixa_valor": {"min": 20, "max": 50_000},
    "armadilhas": [
      {"descricao": "Investimento em consórcio de imóvel", "pode_confundir_com": "Moradia", "motivo": "Envolve imóvel, mas trata-se de uma aplicação/investimento financeiro, não despesa de moradia"},
      {"descricao": "Compra de ouro investimento", "pode_confundir_com": "Outras", "motivo": "Pode parecer compra de bem/joia, mas a finalidade declarada é investimento financeiro"},
      {"descricao": "Investimento em startups", "pode_confundir_com": "Serviços", "motivo": "Pode ser confundido com contratação de consultoria/serviço, mas trata-se de aporte de capital"}
    ]
  },
  {
    "categoria": "OUTRAS",
    "descricoes": [
      "Saque em caixa eletrônico", "Transferência Pix", "Presente de aniversário",
      "Doação", "Compra diversa", "Multa", "Taxa bancária", "Tarifa de manutenção de conta",
      "Rifa", "Aposta esportiva", "Vaquinha online", "Compra em brechó",
      "Item perdido/reembolso", "Troco não identificado", "Câmbio de moeda",
      "Compra internacional não identificada", "Doação para ONG",
      "Presente de casamento", "Contribuição sindical", "Taxa de cartório",
      "Saque emergencial", "Pix não identificado", "Transferência TED",
      "Compra em bazar", "Empréstimo a amigo", "Ajuda financeira família",
      "Compra em leilão", "Cota de rateio de churrasco", "Presente de dia das mães",
      "Presente de natal", "Doação de campanha", "Vaquinha do trabalho",
      "Compra de rifa beneficente", "Reembolso de viagem", "Estorno não identificado",
      "Taxa de emissão de documento", "Segunda via de documento",
      "Taxa de serviço bancário", "Multa de biblioteca", "Compra de bilhete de loteria",
      "Doação de sangue custo transporte", "Contribuição condominial extra",
      "Taxa de associação de bairro", "Anuidade de clube",
      "Taxa de inscrição em sorteio", "Compra não reconhecida",
      "Cobrança duplicada estorno", "Presente surpresa", "Doação para vaquinha médica",
      "Compra em feira de trocas",
      "Saque no banco 24h", "Transferência DOC", "Presente de formatura",
      "Presente de dia dos namorados", "Presente de dia dos pais",
      "Doação para instituição de caridade", "Doação para igreja", "Dízimo",
      "Contribuição para vaquinha de acidente", "Multa de trânsito não identificada",
      "Taxa de saque internacional", "IOF de compra internacional",
      "Taxa de conversão de moeda", "Compra em duty free", "Câmbio para viagem",
      "Compra de bilhete de rifa solidária", "Aposta em cassino online",
      "Aposta em bingo", "Jogo do bicho", "Compra em bazar beneficente",
      "Compra em brechó de roupas infantis", "Item comprado em grupo de Facebook",
      "Compra via Instagram não identificada", "Compra via WhatsApp não identificada",
      "Taxa de cartório de nascimento", "Taxa de cartório de casamento",
      "Segunda via de RG", "Segunda via de CPF", "Taxa de emissão de passaporte",
      "Taxa de visto de viagem", "Multa de atraso de biblioteca pública",
      "Taxa de associação de moradores", "Contribuição para associação de classe",
      "Anuidade de sindicato", "Taxa de inscrição em maratona",
      "Taxa de inscrição em corrida de rua", "Compra de camiseta de evento",
      "Doação para vaquinha de formatura", "Doação para vaquinha de viagem de amigo",
      "Presente para chá de bebê", "Presente para chá de panela",
      "Contribuição para amigo oculto", "Taxa bancária de TED",
      "Taxa de saque em outro banco", "Estorno de compra com cartão clonado",
      "Bloqueio e reemissão de cartão taxa", "Compra não identificada na fatura",
      "Cobrança de assinatura cancelada não identificada",
      "Doação para campanha de vacinação de pet", "Presente de dia das crianças"
    ],
    "faixa_valor": {"min": 5, "max": 600},
    "armadilhas": [
      {"descricao": "Presente de aniversário", "pode_confundir_com": "Lazer", "motivo": "presentes têm caráter social/festivo, podendo remeter a lazer"},
      {"descricao": "Taxa de cartório", "pode_confundir_com": "Serviços", "motivo": "envolve pagamento por um serviço prestado, ambíguo com a categoria Serviços"},
      {"descricao": "Aposta esportiva", "pode_confundir_com": "Lazer", "motivo": "é uma atividade de entretenimento, mas com natureza financeira de risco distinta"}
    ]
  },
  {
    "categoria": "GANHOS",
    "descricoes": [
      "Salário", "Décimo terceiro salário", "Adiantamento de salário", "Hora extra",
      "Comissão de vendas", "Bônus de desempenho", "Participação nos lucros (PLR)",
      "Freelance de design", "Freelance de programação", "Freelance de tradução",
      "Venda de produto usado", "Venda de roupas usadas", "Venda de eletrônico usado",
      "Venda no Mercado Livre", "Venda no OLX", "Venda de artesanato",
      "Renda de aluguel de imóvel", "Renda de aluguel de quarto",
      "Aluguel de temporada recebido (Airbnb)", "Dividendos de ações",
      "Rendimento de fundo imobiliário", "Rendimento da poupança", "Rendimento de CDB",
      "Restituição de imposto de renda", "Reembolso de despesa médica plano de saúde",
      "Reembolso de viagem corporativa", "Cashback de cartão de crédito",
      "Cashback de compras", "Prêmio de loteria", "Prêmio de sorteio",
      "Ganho em aposta esportiva", "Rendimento de aluguel de carro por app",
      "Pix recebido de cliente", "Transferência recebida de familiar",
      "Presente em dinheiro", "Doação recebida", "Vaquinha recebida",
      "Venda de curso online", "Renda de afiliado", "Comissão de marketing de afiliados",
      "Monetização do YouTube", "Monetização do TikTok", "Doação via Twitch (subs/bits)",
      "Renda de venda de fotos stock", "Renda de aula particular",
      "Renda de consultoria prestada", "Renda de plantão extra",
      "Pagamento de projeto freelancer", "Recebimento de dívida antiga",
      "Pagamento de empréstimo feito a amigo", "Reembolso de compra cancelada",
      "Estorno de cobrança indevida", "Restituição de seguro", "Indenização de seguro",
      "Acordo trabalhista recebido", "Verba rescisória", "Seguro-desemprego",
      "Auxílio emergencial governo", "Bolsa família", "Pensão recebida",
      "Pensão alimentícia recebida", "Herança recebida",
      "Doação de familiar para investimento", "Renda de day trade",
      "Ganho de swing trade", "Lucro na venda de ações", "Lucro na venda de criptomoeda",
      "Renda passiva de blog", "Renda de anúncios em site", "Renda de e-book vendido",
      "Renda de curso gravado vendido", "Comissão de indicação",
      "Bônus de indicação de emprego", "Prêmio de produtividade no trabalho",
      "Gorjeta recebida", "Caixinha recebida", "Renda extra de motorista de app",
      "Renda extra de entregador de app", "Renda de venda de comida caseira",
      "Renda de doces por encomenda", "Renda de bolo por encomenda",
      "Renda de brechó online", "Renda de revenda de produtos",
      "Renda de representação comercial", "Comissão de corretagem de imóvel",
      "Comissão de corretagem de seguro", "Renda de aluguel de equipamento",
      "Renda de aluguel de ferramenta", "Prêmio de concurso público", "14º salário",
      "Adicional noturno", "Adicional de periculosidade", "Adicional de insalubridade",
      "Vale cultura recebido", "Vale alimentação extra", "Ressarcimento de home office",
      "Ajuda de custo recebida", "Diária de viagem a trabalho recebida",
      "Renda de sublocação", "Recebimento de nota promissória"
    ],
    "faixa_valor": {"min": 20, "max": 15_000},
    "armadilhas": [
      {"descricao": "Cashback de compras", "pode_confundir_com": "Outras", "motivo": "pode ser confundido com estorno avulso em vez de ganho recorrente"},
      {"descricao": "Reembolso de despesa médica plano de saúde", "pode_confundir_com": "Saúde", "motivo": "está relacionado a gasto de saúde, mas o valor em si é uma entrada de dinheiro, não despesa"},
      {"descricao": "Renda extra de motorista de app", "pode_confundir_com": "Transporte", "motivo": "está associado a transporte, mas representa ganho e não despesa com deslocamento"}
    ]
  }
]