spring.application.name=api

admin-application=true
admin-application-username=root
admin-application-password=root

spring.datasource.url=jdbc:h2:file:./data/financeai

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

auth.token.duracao-horas=${AUTH_TOKEN_DURATION_HOURS:1}

predict_api.host=${API_PREDICT_HOST}
predict_api_key.header_name=${API_KEY_PREDICT_HEADER_NAME}
predict_api_key=${API_KEY_PREDICT}
