spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

oci.object-storage.namespace=${OCI_NAMESPACE}
oci.object-storage.bucket-name=${OCI_BUCKET_NAME}
oci.object-storage.region=${OCI_REGION}
oci.object-storage.access-key=${OCI_S3_ACCESS_KEY}
oci.object-storage.secret-key=${OCI_S3_SECRET_KEY}
oci.object-storage.prefix=${OCI_PREFIX}