spring.application.name=api

# banco padrão se nada for informado
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

admin-application=true
admin-application-username=root
admin-application-password=root

auth.token.duracao-horas=${AUTH_TOKEN_DURATION_HOURS:1}

predict_api.host=${API_PREDICT_HOST}
predict_api_key.header_name=${API_KEY_PREDICT_HEADER_NAME}
predict_api_key=${API_KEY_PREDICT}
